- frontend/src/pages/AdminPortal/AdminHomePage.vue
> Made UL into buttons, added icons

- frontend/src/App.vue
- frontend/src/pages/HomePage.vue
it should work, but mobile emulation mode in chrome isnt too accurate so im not 100% sure
> made overflow-x and overflow-y hidden

- frontend/src/components/CourseTable.vue
- frontend/src/components/CourseTableCourse.vue
- frontend/src/components/MyPathway.vue
- frontend/src/components/PathwayCategory.vue
- frontend/src/main.js
- frontend/src/pages/MyPathways/MyPathwaysPage.vue
- frontend/src/pages/Pathway/PathwayPage.vue
> James issues changes

- frontend/src/pages/AdminPortal/AdminSearchCCPage.vue
> Add remove button to Admin pathways page

- frontend/src/pages/AdminPortal/AdminHomePage.vue
made the "fake" buttons into vue buttons
> changed btns to v-btn

- frontend/src/pages/FromClasses/FromClassesPage.vue
when you select by classes, it now says what you selected on top
Closes #71
> added selection bar

- frontend/src/pages/About/AboutPage.vue
- frontend/src/pages/FromClasses/FromClassesPage.vue
- frontend/src/plugins/vuetify.js
Complete facelift to the FAQ/about page:
AboutPage.vue :
- changed header text
- changed html unordered list to v-expansion-panels to make them dropdown menus
- styling of the dropdown menus
- added open/close all buttons
- added a method for open/close button functionality
FromClasses.vue and vuetify.js :
- fixed minor whitespace issues that were causing errors at build time
> 93: faq page dropdowns

- frontend/src/components/YearSelection.vue
- frontend/src/main.js
- frontend/src/pages/FromClasses/FromClassesPage.vue
- frontend/src/pages/FromClasses/FromClassesPathways.vue
- frontend/src/pages/HomePage.vue
- frontend/src/pages/MyPathways/APathwayPage.vue
- frontend/src/pages/MyPathways/MyPathwaysPage.vue
- frontend/src/pages/Pathway/PathwayPage.vue
- frontend/src/pages/Pathway/PathwaysPage.vue
Added a dropdown menu onto several pages in accordance with #88, though it does not actually change the course offerings or attributes as it would if it actually were in previous years. The user's choice is preserved across refreshes and pages.
> Year selection menu

- frontend/src/pages/FromClasses/FromClassesPage.vue
> removed duplicate buttons

- frontend/src/pages/Pathway/PathwaysPage.vue
Reverts anderm18/HASSPathways#98
> Revert "James issues changes"

- frontend/src/pages/FromClasses/FromClassesPage.vue
Closes #97 
customized scrollbar for all pages
> customized scrollbar

- backend/scrapers/courses_scraper.py
- frontend/src/components/CourseTableCourse.vue
- frontend/src/components/MyPathway.vue
- frontend/src/data/json/courses.json
- frontend/src/pages/AdminPortal/AdminSearchCCPage.vue
- frontend/src/pages/FromClasses/FromClassesPage.vue
Closes #101. The cross listing is not shown on any of the forms on the admin portal, and admin have no way as of yet to add/edit/remove cross listings, but they should be present everywhere else.
> Crosslisting display

- frontend/src/pages/About/AboutPage.vue
> added padding

- frontend/src/components/Header.vue
- frontend/src/components/YearSelection.vue
- frontend/src/pages/FromClasses/FromClassesPage.vue
- frontend/src/pages/FromClasses/FromClassesPathways.vue
- frontend/src/pages/HomePage.vue
- frontend/src/pages/MyPathways/MyPathwaysPage.vue
- frontend/src/pages/Pathway/PathwayPage.vue
- frontend/src/pages/Pathway/PathwaysPage.vue
> Moved year selection button to header

- frontend/src/components/DarkLightModeButton.vue
- frontend/src/pages/FromClasses/FromClassesPathways.vue
Felt crucial since the final thing is out soon.
> Fixed the outdated instructions

- frontend/src/pages/About/AboutPage.vue
Closes #129 
i dont know where putting the catalog link would look the best so i just slapped it on the screen for now. I rmbr from the meeting bram saying something about having the official catalog link on the site somewhere so yea.
> Added catalog link to about page

- frontend/src/pages/AdminPortal/AdminPathwayPage.vue
- frontend/src/pages/AdminPortal/AdminSearchCCPage.vue
Closes #131
I just removed the rounding of the components so that they match the other components in the admin pages
> Unrounded the components

- frontend/src/components/Bookmark.vue
- frontend/src/components/CourseTable.vue
- frontend/src/components/CourseTableCourse.vue
- frontend/src/components/CourseTableModifiers.vue
- frontend/src/components/Footer.vue
- frontend/src/components/MyPathway.vue
- frontend/src/data/course-modifiers.js
- frontend/src/pages/MyPathways/MyPathwaysPage.vue
- frontend/src/pages/Pathway/PathwayPage.vue
- frontend/src/pages/Pathway/PathwaysPage.vue
shouldnt break everything this time
- graph view is now pretty much done
- pre-requisites are here now too
- footer is sticky again
- the pathway from courses page actually shows up now
> Graph view PR part 2

- frontend/src/components/DarkLightModeButton.vue
THE SWITCH IS FINALLY FULLY FIXED!
> Dicosn issues

- backend/scrapers/pathway_scraper.py
- frontend/src/data/json/pathways.json
> Removes Required-Remaining duplicates

- frontend/src/components/Header.vue
> Changed zindex of header, now in front of check boxes

- frontend/src/components/CourseTable.vue
- frontend/src/pages/FromClasses/FromClassesPage.vue
Added feature of sorting by ID which allows user to find classes based on ID quickly. @PlayX-2333
> Sorting option

- frontend/src/pages/Courses/CoursePage.vue
Modified the behavior of the expansion cards for sections on course pages. Now, buttons are tied only to the sections a specific professor teaches.
> Section Expansion Cards

- frontend/src/router/index.js
#196 
- delete extra button on the homepage that is linking to an unfinished feature
- get rid of the endpoint in the Vue router
> Deleted Extra Button 

- frontend/src/components/CourseTableCourse.vue
> Fixed course link selection

- frontend/src/components/CourseTableCourse.vue
closes #231 , made the course link open by clicking the title of the course.
> Made the course link be in the title of the course

- frontend/src/components/CourseTableCourse.vue
closes #234 removed unnecessary code which caused the lag
> Fixed lag when selecting class

- frontend/src/data/json/2023-2024/pathways.json
Works on #217 
Fix some issues with the descriptions of some pathways.
> Reformated Pathway Descriptions

- frontend/src/components/CourseTableCourse.vue
Closes #237 
Underlines and now fits within text of link
> Fix Course Link Width

- frontend/src/components/MyPathway.vue
closes #239 also formatted the title to match the rest of the website
> Add Link In Matching Pathways Page

- frontend/src/pages/Courses/CoursePage.vue
> When in a course show which pathways include this course

- frontend/src/components/PathwayTableCourse.vue
- frontend/src/components/SearchPageCourseDisplay.vue
- frontend/src/pages/HomePage.vue
- frontend/src/pages/Search/Search.vue
- frontend/src/router/index.js
> added search bar and search page
